name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3

      - name: Configurar Flutter
        uses: flutter-actions/setup-flutter@v2
        with:
          flutter-version: '3.32.6'

      - name: Verificar versi칩n de Flutter
        run: flutter --version

      - name: Obtener dependencias
        run: flutter pub get

      - name: Verificar formato del c칩digo
        run: dart format --set-exit-if-changed .

      - name: Ejecutar an치lisis est치tico
        run: flutter analyze

